# Generated by Django 5.2.4 on 2025-07-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='feedbackus',
        ),
    ]
